version: '2'
services:
  web:
    environment:
      - PORT=3000
      - CRONTAB=* * * * *
    build: .
    command: yarn start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"